flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git://github.com/strokyl/xmonad-contrib.git
    commit: master
  extra-dep: true
extra-deps:
- X11-1.6.1.2
- X11-xft-0.3.1
- xmonad-0.12
resolver: lts-8.3
